"""
About Page
CycleSense
"""

import streamlit as st

st.set_page_config(
    page_title="About | CycleSense",
    page_icon="🌸",
    layout="wide"
)

# -----------------------------------------------------

st.title("🌸 About CycleSense")

st.markdown("---")

st.header("Project Overview")

st.write("""
**CycleSense** is a research-inspired machine learning application that predicts
the **Estimated Day of Ovulation** from menstrual cycle characteristics.

The project was developed to demonstrate an end-to-end machine learning workflow,
including:

- Data Cleaning
- Exploratory Data Analysis
- Feature Engineering
- Regression & Classification
- Model Explainability (SHAP)
- Streamlit Deployment

The goal is to showcase how machine learning techniques can be applied to
women's health datasets while maintaining transparency and interpretability.
""")

# -----------------------------------------------------

st.markdown("---")

st.header("Research Motivation")

st.write("""
Understanding menstrual cycle patterns is important for fertility awareness,
cycle tracking, and reproductive health research.

This project investigates how cycle-related features influence the estimated
day of ovulation by building predictive machine learning models using a
publicly available menstrual cycle dataset.

The project emphasizes:

- Data-driven decision making
- Explainable AI
- Reproducible ML pipelines
- Healthcare-oriented analytics
""")

# -----------------------------------------------------

st.markdown("---")

st.header("Dataset")

st.write("""
The project uses the **Federal Menstrual Cycle Dataset**, which contains
information collected from women tracking their menstrual cycles.

The dataset includes:

- Cycle Length
- Estimated Ovulation Day
- Length of Luteal Phase
- Menstrual Bleeding Scores
- BMI
- Age
- Fertility Indicators
- Lifestyle Factors

The dataset contains approximately:

- **1,600+ menstrual cycles**
- **70+ features**
- Regression and classification targets
""")

# -----------------------------------------------------

st.markdown("---")

st.header("Machine Learning Workflow")

st.code(
"""
Raw Dataset
      ↓
Data Cleaning
      ↓
Feature Engineering
      ↓
Regression Models
      ↓
Classification Models
      ↓
Model Comparison
      ↓
SHAP Explainability
      ↓
Streamlit Deployment
"""
)

# -----------------------------------------------------

st.markdown("---")

st.header("Models Evaluated")

col1, col2 = st.columns(2)

with col1:

    st.subheader("Regression")

    st.write("""
    • Linear Regression

    • Ridge Regression

    • Random Forest Regressor

    • Gradient Boosting Regressor
    """)

with col2:

    st.subheader("Classification")

    st.write("""
    • Logistic Regression

    • Random Forest Classifier

    • Gradient Boosting Classifier
    """)

# -----------------------------------------------------

st.markdown("---")

st.header("Best Performing Models")

col1, col2 = st.columns(2)

with col1:

    st.metric(
        label="Regression",
        value="Gradient Boosting"
    )

with col2:

    st.metric(
        label="Classification",
        value="Gradient Boosting"
    )

# -----------------------------------------------------

st.markdown("---")

st.header("Technologies Used")

tech1, tech2, tech3 = st.columns(3)

with tech1:

    st.write("""
### Programming

- Python
- Pandas
- NumPy
    """)

with tech2:

    st.write("""
### Machine Learning

- Scikit-learn
- SHAP
- Joblib
    """)

with tech3:

    st.write("""
### Visualization

- Matplotlib
- Seaborn
- Streamlit
    """)

# -----------------------------------------------------

st.markdown("---")

st.header("Project Structure")

st.code("""
CycleSense/

├── app/
├── data/
├── models/
├── notebooks/
├── reports/
├── research/
├── src/
├── README.md
└── requirements.txt
""")

# -----------------------------------------------------

st.markdown("---")

st.header("Future Improvements")

st.write("""
Potential future enhancements include:

- Integration with wearable device data (Fitbit, Apple Health)
- Menstrual phase prediction
- Personalized cycle forecasting
- Deep learning models (LSTM)
- Confidence intervals for predictions
- Clinical validation using external datasets
""")

# -----------------------------------------------------

st.markdown("---")

st.warning("""
### Medical Disclaimer

CycleSense is intended **only for educational and research purposes**.

The predictions generated by this application should **not** be used
for medical diagnosis, fertility planning, treatment decisions, or
clinical practice.

Always consult a qualified healthcare professional for medical advice.
""")

# -----------------------------------------------------

st.caption(
    "CycleSense • Research-Based Ovulation Prediction using Machine Learning"
)